### ISSUE TITLE
Add `settle` feature

### ISSUE THREAD

**Issue by developernaren** [clue/reactphp-block#48]
Can we introduce something like this?

http://docs.guzzlephp.org/en/stable/quickstart.html?highlight=settle

```
// Wait for the requests to complete, even if some of them fail
$responses = Promise\settle($promises)->wait();

// Values returned above are wrapped in an array with 2 keys: "state" (either fulfilled or rejected) and "value" (contains the response)
echo $responses['image']['state']; // returns "fulfilled"
echo $responses['image']['value']->getHeader('Content-Length')[0];
echo $responses['png']['value']->getHeader('Content-Length')[0];
```

I am working on a project where I would need to request to bunch of urls, where I process the `urls` if they are successful, and ignore the one that fail. I am trying to use this in combination with [react/buzz](https://github.com/clue/reactphp-buzz).

**Comment by clue** [comment]
@developernaren Thanks for reporting!

Have you seen https://github.com/clue/reactphp-block/issues/29 and https://github.com/EmchBerger/react-settle-promise?

I understand where you're coming from and I agree that there is *some* value in this addition, but I'm not sure about an API that I feel comfortable providing support for. Having an array with `state` and `value` keys doesn't sound like something I'd like enjoy maintaining for years to come.

As an alternative, you always use functional composition to build this yourself with just a few lines of code, so I'm not sure how much value it actually provides.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
